### ISSUE TITLE
[버그]  이미지 폴더 중복

### ISSUE THREAD

**Issue by Yeom-JinHo** [5-TAYO/SSEUKTUDY#10]
## ⚠️ 버그 설명
![스크린샷 2022-05-30 오전 10 55 48](https://user-images.githubusercontent.com/81306489/170903863-ef9a4e16-8e4f-4e30-9260-d5cafcdbed8e.png)
![스크린샷 2022-05-30 오전 11 01 34](https://user-images.githubusercontent.com/81306489/170903886-abbcf868-49f2-4339-9c01-99ed7b1352ae.png)

버그 설명

이미지 폴더구조 셋팅 중복 ㅠㅡㅠ

## 📑 완료 조건

- [x] 이미지 정상 임포트, Craco 재설정

**Comment by jmlee9707** [comment]
굳!
