### ISSUE TITLE
[BE] 유저 API 리펙토링

### ISSUE THREAD

**Issue by gandi0330** [5-TAYO/SSEUKTUDY#73]
## :hammer: 기능 설명

기능 설명

## 📑 완료 조건

- [x] 유저 등록 API 
- [x] 유저 수정 API
- [x] 유저 삭제 API
- [x] 로그인 API
- [x] 로그아웃 API
- [x]  유저 정보조회 API
- [x] 리프레쉬 토큰 발급 API

**Comment by lion1735** [comment]
유저 수정, 정보조회 부분 카테고리 미구현
