### ISSUE TITLE
[버그] 스터디리스트 등록일순 조회시 중복문제 

### ISSUE THREAD

**Issue by Yeom-JinHo** [5-TAYO/SSEUKTUDY#82]
## ⚠️ 버그 설명

스터디리스트 등록일순 조회시 중복문제 
리스트 조회 중 삽입이 발생하면 스터디배열이 중복되어서
똑같은 값이 렌더링 되는 문제

## 📑 완료 조건

- [ ] 중복제거 해결

**Comment by gandi0330** [comment]
이미 조회한 스터디의 마지막 id를 입력으로 받아 해당 id 이후의 스터디를 제공하는 방법 고려

**Comment by gandi0330** [comment]
페이징 문제 발생!! 

커서 페이징에 관한 간단한 설명

- 페이징 방법 2가지
- 1. 오프셋 페이징
- 2. 커서 페이징

오프셋 페이징
- db에서 특정 테이블에 (mysql) limit 을 활용하여 0행부터 10개, 10행부터 10개 .. 이런 방법으로 행을 가져오는 방법
``` sql
select * from study offset 0 limit 10
select * from study offset 10 limit 20
.
.
```
-> 문제점 : 중간에 데이터 삽입이나 삭제가 일어나면 겹치거나 보이지 않는 행이 생김
페이지네이션을 오프셋 페이징으로 구현할 경우 (크게 체감 안됨)
무한 스크롤을 오프셋 페이징으로 구현할 경우 (크게 체감 됨)

커서 페이징
- db에서 특정 테이블의 열을 기준으로 가져오는 것
``` sql
select * from study where studyId > {입력할 studyId} order by studyId limit 10
```

-> 문제점 : 특정 열이 정렬되어있어야만 사용 가능 -> 스터디의 등록일 순은 가능하지만 스터디 조회수와 좋아요 순으로 정렬하면 행에 순차적인 열이 없어서 불가능함

요약 : 무한스크롤 하려면 등록일순만 가능, 좋아요 순이랑 조회수 순으로 정렬할거면 페이지네이션

참고 : https://bbbicb.tistory.com/40

```
// 오프셋
select * from `table` limit 0, 2;
delete from `table` where studyId = 1;
select * from `table` limit 2, 2;

// 커서
select * from `table` where studyId > 0 limit 2;
delete from `table` where studyId = 1;
select * from `table` where studyId > 2 limit 2;

```
