### ISSUE TITLE
[버그] 스터디 전체 조회 조회수순 정렬 오류

### ISSUE THREAD

**Issue by Yeom-JinHo** [5-TAYO/SSEUKTUDY#93]
## ⚠️ 버그 설명

스터디 전체 조회 조회수순 정렬 오류

좋아요순, 등록일순은 정상 작동 

> ### 포스트맨 요청 500에러
![스크린샷 2022-07-01 오후 11 38 18](https://user-images.githubusercontent.com/81306489/176915838-8fa0aea3-99c1-4400-b05b-76d1e46af607.png)

> ### study.xml 쿼리
![스크린샷 2022-07-01 오후 11 38 27](https://user-images.githubusercontent.com/81306489/176915842-d8a00743-8038-4a15-bf36-7133d82364ef.png)

## 📑 완료 조건

- [x] 스터디 전체 조회 죄회순 정렬

**Comment by lion1735** [comment]
역정렬이 되는건가요?

**Comment by Yeom-JinHo** [comment]
아뇨 아예 500에러로 데이터가 안넘어옵니다. (조회수 정렬시)

**Comment by gandi0330** [comment]
@Yeom-JinHo 해결했습니다 확인해주시고 이슈 닫아주세욥
